// DETAILS
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

// CHECKOUT
export const CHECKOUT_MEAL = "CHECKOUT_MEAL";
export const PURCHASE_MEAL = "PURCHASE_MEAL";

// PURCHASE COUNT
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const INITIALIZE_ITEM = "INITIALIZE_ITEM";
